### ISSUE TITLE
model error

### ISSUE THREAD

**Issue by limitforever** [karlhl/Bert-classification-pytorch#1]
2021-06-10 14:50:50.656904: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/lida/Downloads/Bert-classification-pytorch-main/src/train.py", line 229, in <module>
    classifier = transformers_bert_binary_classification()
  File "/Users/lida/Downloads/Bert-classification-pytorch-main/src/train.py", line 22, in __init__
    self.device_setup()
  File "/Users/lida/Downloads/Bert-classification-pytorch-main/src/train.py", line 60, in device_setup
    self.model = bert_lr_last4layer(bert_lr_last4layer_Config())
  File "/Users/lida/Downloads/Bert-classification-pytorch-main/src/bert_lr_last4layer.py", line 42, in __init__
    self.bert = BertModel.from_pretrained(config.bert_path,config = config.config_path,from_tf=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 696, in from_pretrained
    model = load_tf2_checkpoint_in_pytorch_model(model, resolved_archive_file, allow_missing_keys=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/modeling_tf_pytorch_utils.py", line 261, in load_tf2_checkpoint_in_pytorch_model
    tf_model.load_weights(tf_checkpoint_path, by_name=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2323, in load_weights
    hdf5_format.load_weights_from_hdf5_group_by_name(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 790, in load_weights_from_hdf5_group_by_name
    raise ValueError('Layer #' + str(k) +' (named "' + layer.name +
ValueError: Layer #0 (named "bert"), weight <tf.Variable 'tf_bert_model/bert/encoder/layer_._0/attention/self/query/kernel:0' shape=(768, 768) dtype=float32, numpy=
array([[ 0.01161919,  0.0218157 ,  0.01187958, ..., -0.01535313,
         0.02423065,  0.00286917],
       [-0.01926546,  0.01164436,  0.01635618, ..., -0.01244493,
         0.00410933,  0.00290847],
       [ 0.00971076, -0.01796716, -0.00646344, ..., -0.00639564,
        -0.00196607,  0.02563113],
       ...,
       [-0.00057331,  0.02970757, -0.00457912, ...,  0.00428701,
         0.00676068,  0.01667783],
       [-0.0056886 , -0.00575277, -0.00499384, ..., -0.01303921,
        -0.00428751, -0.00822998],
       [-0.01652718,  0.00356799,  0.00806794, ...,  0.02051857,
         0.00855278, -0.02079186]], dtype=float32)> has shape (768, 768), but the saved weight has shape (768, 12, 64).

Process finished with exit code 1

**Comment by limitforever** [comment]
How can I solve this problem?
